[blockchain]
provider = "ws://127.0.0.1:9944"
storage_address="5CGLS8pNzeSHyouMK6tH59RVFRPX2pA7H3PSPhcENNbW5Ekm"
verifier_address="5FCK2F1S6UGHheEo2fDk2dhUtHcH4A38BQ8xVwCKxnLVMsCw"

[node]
port = 5000

[middle_node]
url="http://127.0.0.1:5005"


