[blockchain]
provider = "ws://127.0.0.1:9944"
storage_address="5G8JK5375aAMYjqqvcf9ZAE626kwDXnh6np9qNaJH7tEhJyp"
verifier_address="5Cy2W21yP4pLijoXv88ybcFoSWBN96MSU4geednPMRQketwQ"

[node]
port = 5000

[middle_node]
url="http://127.0.0.1:5005"


