[blockchain]
provider = "ws://127.0.0.1:9944"
storage_address="5DUyxhb4EMso7qmXUH5ySuKCEbQoy2w6JSt1zfzo1zsRYQrc"
verifier_address="5CqhDE3ch6m3oP4sLsBKx1JdreRP22wpVoS16wYXbRWTZqCN"

[node]
port = 5000

[middle_node]
url="http://127.0.0.1:5005"


